// backend/src/services/discordInteractiveAuction.js
import admin from 'firebase-admin';
import { ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from 'discord.js';
import { getGateStatusDetails } from '../config/timeWindow.js'; // ⏰ Timeline Intersector: Imports master clock calculations

// Pure message text block formatting the in-game display alignment rule
const IN_GAME_TAB_REMINDER = `🚩 **PLEASE READ!!**:\n` +
  `> Please make sure to **click** the **[GUILD AUCTION]** and **[ALL]** Tab on your in-game auction book screen! ` +
  `This guarantees your game client layout matches our Request Page and Slot numbering system.`;

/**
 * ⚙️ CORE COMPILER: Calculates book geometry coordinates dynamically in runtime memory
 * Projects a pure Single Source of Truth layout map out of Phase 2 flat allocation arrays.
 */
function computeVirtualMatrix(items, categoryAllocations, qtyPerPage = 4) {
  let currentVirtualPage = 1, currentVirtualSlot = 1;
  const matrix = [];

  items.forEach(item => {
    // 🛡️ Type Guard: Ensures object maps generated by Firebase under high-concurrency are normalized back to arrays
    const rawSelectedNode = categoryAllocations[item.id]?.selected;
    const flatBoxArray = Array.isArray(rawSelectedNode)
      ? rawSelectedNode
      : Object.values(rawSelectedNode || {});

    flatBoxArray.forEach((playerName, index) => {
      matrix.push({
        itemType: item.id,
        itemName: item.name,
        index: index, // Stores the true flat index reference position
        page: currentVirtualPage,
        slot: currentVirtualSlot,
        name: playerName === "" ? "" : playerName
      });

      currentVirtualSlot++;
      if (currentVirtualSlot > qtyPerPage) {
        currentVirtualSlot = 1;
        currentVirtualPage++;
      }
    });
  });
  return matrix;
}

/**
 * 🛰️ HELPER: Dynamically generates the real-time personal ledger claim summary text block
 */
function compileUserClaimsSummary(virtualMatrix, finalRosterName) {
  const matchingClaims = virtualMatrix.filter(slot => slot.name === finalRosterName);

  if (matchingClaims.length === 0) {
    return `📦 **YOUR REQUEST LIST SUMMARY**:\n*• No item slot coordinates secured yet during this session.*`;
  }

  const listLines = matchingClaims.map(slot => 
    `• **${slot.itemName}** ➔ Page ${slot.page}, Slot ${slot.slot}`
  );

  return `📦 **YOUR REQUEST LIST SUMMARY**:\n${listLines.join('\n')}`;
}

/**
 * 📣 Renders the permanent, pinned public message card containing the launch action button
 */
export async function sendPublicAuctionCard(channel) {
  const embed = new EmbedBuilder()
    .setTitle('⚔️ LIVE AUCTION INTERACTION PANEL')
    .setDescription('During Live Auction, Please Review and claim remaining vacant item slots right here.\n\nClick the button below to open your personal Request panel.')
    .setColor('#4f46e5');

  const buttonRow = new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId('open_auction_panel')
      .setLabel('🔍 Open My Personal Request Panel')
      .setStyle(ButtonStyle.Primary)
  );

  await channel.send({ embeds: [embed], components: [buttonRow] });
}

/**
 * 🛰️ HELPER: Generates the Master Item Category Selection View (Step 2)
 */
async function renderItemCategoryView(interaction, finalRosterName, prefixMessage = "") {
  const db = admin.database();
  const configSnap = await db.ref('settings/configuration').once('value');
  const sessionSnap = await db.ref('auction/active_session').once('value');

  if (!sessionSnap.exists() || !configSnap.exists()) {
    return await interaction.editReply({ content: '❌ **ERROR**: No active allocation session is currently running on the officer dashboard.', components: [] });
  }

  const { items = [] } = configSnap.val();
  const { categoryAllocations = {}, qtyPerPage = 4 } = sessionSnap.val();

  // Compile dynamic layout map from Phase 2 array blocks
  const virtualMatrix = computeVirtualMatrix(items, categoryAllocations, qtyPerPage);

  const itemVacancyCounts = {};
  virtualMatrix.forEach(slot => {
    if (slot.name === "") {
      itemVacancyCounts[slot.itemType] = (itemVacancyCounts[slot.itemType] || 0) + 1;
    }
  });

  const gateDetails = getGateStatusDetails() || {};
  const activeEventObj = configSnap.val().events?.[gateDetails.activeEventId];
  const activeLoots = activeEventObj?.loots || {};

  const menuOptions = items
    .filter(item => activeLoots[item.id] !== undefined && (itemVacancyCounts[item.id] || 0) > 0)
    .map(item => ({
      label: item.name,
      description: `${itemVacancyCounts[item.id]} empty layout slots available.`,
      value: `select_item_${item.id}`
    }));

  const userClaimsSummaryText = compileUserClaimsSummary(virtualMatrix, finalRosterName);

  if (Object.keys(activeLoots).length === 0) {
    return await interaction.editReply({
      content: `${prefixMessage}\n\n❌ **NO ITEMS SCHEDULED**: There are no items scheduled for registration in tonight's auction cycle.`,
      components: []
    });
  }

  if (menuOptions.length === 0) {
    return await interaction.editReply({ 
      content: `${prefixMessage}\n\n${IN_GAME_TAB_REMINDER}\n\n${userClaimsSummaryText}\n\n🎉 **ALL OPEN SLOTS CLAIMED**: Every single available slots has been filled!`, 
      components: [] 
    });
  }

  const itemSelectMenu = new StringSelectMenuBuilder()
    .setCustomId('auction_select_item_type')
    .setPlaceholder('Select a Loot Category...')
    .addOptions(menuOptions);

  const baseContent = `🔒 **USER INFORMATION**\n👤 Name: **${finalRosterName}**\n\n${IN_GAME_TAB_REMINDER}\n\n${userClaimsSummaryText}\n\nPlease choose an Item category below to view open & available slots:`;

  await interaction.editReply({
    content: prefixMessage ? `${prefixMessage}\n\n${baseContent}` : baseContent,
    components: [new ActionRowBuilder().addComponents(itemSelectMenu)]
  });
}

/**
 * 🛰️ HELPER: Generates the Fast-Tap Button Grid Matrix (Step 3 Upgraded)
 */
async function renderSpecificSlotView(interaction, itemId, finalRosterName, prefixMessage = "") {
  const db = admin.database();
  const configSnap = await db.ref('settings/configuration').once('value');
  const sessionSnap = await db.ref('auction/active_session').once('value');

  const { items = [] } = configSnap.val();
  const { categoryAllocations = {}, qtyPerPage = 4 } = sessionSnap.val();

  const selectedItemObj = items.find(i => i.id === itemId);
  const gateDetails = getGateStatusDetails() || {};
  const activeEventObj = configSnap.val().events?.[gateDetails.activeEventId];
  const maxAllowedLimit = activeEventObj?.loots && activeEventObj.loots[itemId] !== undefined ? activeEventObj.loots[itemId] : 0;

  const virtualMatrix = computeVirtualMatrix(items, categoryAllocations, qtyPerPage);
  const userClaimedCount = virtualMatrix.filter(s => s.itemType === itemId && s.name === finalRosterName).length;

  // Build functional buttons using the index location inside categoryAllocations list maps
  const rawButtonsArray = [];
  virtualMatrix.forEach((slot) => {
    if (slot.itemType === itemId && slot.name === "") {
      rawButtonsArray.push(
        new ButtonBuilder()
          .setCustomId(`claim_slot_btn_${slot.index}_item_${itemId}`) // Maps straight to flat index
          .setLabel(`Page ${slot.page} Slot ${slot.slot}`)
          .setStyle(ButtonStyle.Secondary)
      );
    }
  });

  const userClaimsSummaryText = compileUserClaimsSummary(virtualMatrix, finalRosterName);

  if (userClaimedCount >= maxAllowedLimit) {
    return await renderItemCategoryView(interaction, finalRosterName, `❌ **CLAIM RESTRICTED**: You have reached your capacity limit (**${userClaimedCount}/${maxAllowedLimit}**) for **${selectedItemObj?.name}**.`);
  }

  if (rawButtonsArray.length === 0) {
    return await renderItemCategoryView(interaction, finalRosterName, `⚠️ **CATEGORY EXPIRED**: The remaining slots for **${selectedItemObj?.name}** were just snapped up!`);
  }

  // 🛡️ DYNAMIC CEILING GUARD: Self-calculates the maximum button capacity based on active navigation items
  const utilityRowsReserved = 1; // Rows explicitly claimed by Back/Utility controls
  const totalAvailableSlotRows = 5 - utilityRowsReserved; // Discord maximum absolute limit is 5 rows per view
  const maxSafeButtonCapacity = totalAvailableSlotRows * 5; // Exactly 5 button elements can fit per ActionRow frame

  const cappedButtons = rawButtonsArray.slice(0, maxSafeButtonCapacity);
  const totalComponentRows = [];

  for (let i = 0; i < cappedButtons.length; i += 5) {
    const actionRow = new ActionRowBuilder().addComponents(cappedButtons.slice(i, i + 5));
    totalComponentRows.push(actionRow);
  }

  const backButton = new ButtonBuilder()
    .setCustomId('open_auction_panel_back')
    .setLabel('↩️ Return to Categories')
    .setStyle(ButtonStyle.Danger);

  const utilityRow = new ActionRowBuilder().addComponents(backButton);
  totalComponentRows.push(utilityRow);

  const baseContent = `📋 **Loot Target**: **${selectedItemObj?.name}**\n👤 Your Limit Status: **${userClaimedCount}/${maxAllowedLimit} Claimed**\n\n${IN_GAME_TAB_REMINDER}\n\n${userClaimsSummaryText}\n\nTap any vacant grid coordinate button below to lock your claim instantly:`;

  await interaction.editReply({
    content: prefixMessage ? `${prefixMessage}\n\n${baseContent}` : baseContent,
    components: totalComponentRows
  });
}

/**
 * ⚡ CORE INTERACTION INTERCEPT ROUTINE
 */
export async function handleAuctionInteraction(interaction) {
  const db = admin.database();

  // 🚨 ABSOLUTE EMERGENCY OVERRIDE SHIELD: Instantly terminate all gateway interactions if Forced Lock is active
  const globalConfigSnap = await db.ref('settings/configuration').once('value');
  if (globalConfigSnap.exists() && globalConfigSnap.val().isForceLocked === true) {
    const lockdownNotice = `🚨 **ADMINISTRATIVE LOCKDOWN**: The bidding framework has been completely frozen by management. Discord inputs are currently offline.`;
    if (interaction.deferred || interaction.replied) {
      await interaction.editReply({ content: lockdownNotice, components: [] }).catch(() => {});
    } else {
      await interaction.reply({ content: lockdownNotice, ephemeral: true }).catch(() => {});
    }
    return;
  }

  const finalRosterName = (interaction.member?.nickname || interaction.member?.displayName || interaction.user?.globalName || interaction.user?.username || '').trim();
  // 🛡️ SLASH SHIELD: Added forward slash to the regex catch to prevent directory folder breakages
  const sanitizedFirebaseKey = finalRosterName.replace(/[\.\#\$\/\[\]]/g, '_');

    // ─── STEP 1: USER CLICKS THE PUBLIC ENTRY BUTTON ───
  if (interaction.isButton() && interaction.customId === 'open_auction_panel') {
    await interaction.deferReply({ ephemeral: true });

    // 🛡️ SECURE DISCORD INPUT INTERCEPTOR: Checks the manual override switch on your admin dashboard before accepting inputs
    const sessionSnap = await db.ref('auction/active_session').once('value');
    const isGateOpen = sessionSnap.exists() && sessionSnap.val().isDiscordGateOpen === true;

    if (!isGateOpen) {
      return await interaction.editReply({
        content: `⚠️ **AUCTION PAUSED**: bidding controls are currently muted. Bids are processed only when authorized by Guild Officers on the dashboard.\n\n⏳ *Please stand by for management to broadcast the allocation sequence.*`
      });
    }

    const memberCheckSnap = await db.ref(`auction/members/${sanitizedFirebaseKey}`).once('value');
    if (!memberCheckSnap.exists()) {
      return await interaction.editReply({
        content: `⚠️ **ROSTER DISCONNECT**: Your Discord identity (**${finalRosterName}**) is not linked to an active guild roster row.\n\n👉 *Please tell to a Guild officer to Synchronize the web app profile again.*`
      });
    }

    await renderItemCategoryView(interaction, finalRosterName);
  }

  // ─── LOOPBACK JUMP: USER CLICKS THE BACK BUTTON INSIDE THE CORE WORKFLOW ───
  if (interaction.isButton() && interaction.customId === 'open_auction_panel_back') {
    await interaction.deferUpdate();
    await renderItemCategoryView(interaction, finalRosterName);
  }

  // ─── STEP 2: USER SELECTS AN ITEM CATEGORY DROPDOWN ───
  if (interaction.isStringSelectMenu() && interaction.customId === 'auction_select_item_type') {
    await interaction.deferUpdate();
    const itemId = interaction.values[0].replace('select_item_', '');
    await renderSpecificSlotView(interaction, itemId, finalRosterName);
  }

  // ─── STEP 3 & 4: USER TAPS A SPECIFIC GRID CANVAS BUTTON MATRIX CELL ───
  if (interaction.isButton() && interaction.customId.startsWith('claim_slot_btn_')) {
    await interaction.deferUpdate();
    
    const rawValueToken = interaction.customId.replace('claim_slot_btn_', '');
    const valueParts = rawValueToken.split('_item_');

    const targetIndex = parseInt(valueParts[0], 10);
    const itemId = valueParts[1];

    try {
        // 🛰️ ATOMIC ALLOCATION INTERSECTOR: Mutates the true nested Phase 2 index field directly
      const txResult = await db.ref(`auction/active_session/categoryAllocations/${itemId}/selected`).transaction((currentSelected) => {
        if (!currentSelected) return currentSelected;

        // Anti-collision guard: Check if someone beat them to it
        if (currentSelected[targetIndex] !== "") {
          return; // 🛑 Return undefined to abort transaction safely without breaking internal Firebase engine loops
        }

        currentSelected[targetIndex] = finalRosterName;
        return currentSelected;
      });

      // If the transaction aborted because another thread claimed it first, trigger collision handler
      if (!txResult.committed) {
        throw new Error('COLLISION_DETECTED');
      }

      // 🚀 CONCURRENCY OPTIMIZATION: Extract the newly updated array states from memory 
      // instead of re-reading the entire 'auction/active_session' data tree across the network
      const updatedConfigSnap = await db.ref('settings/configuration').once('value');
      const localSessionCacheSnap = await db.ref('auction/active_session').once('value');
      
      const finalItems = updatedConfigSnap.val().items || [];
      const sessionCacheObj = localSessionCacheSnap.val() || {};
      const finalQtyPerPage = sessionCacheObj.qtyPerPage || 4;
      
      // Inject the atomic array patch directly into our local session cache memory block
      const finalAllocations = sessionCacheObj.categoryAllocations || {};
      if (finalAllocations[itemId]) {
        finalAllocations[itemId].selected = txResult.snapshot.val();
      }

      const freshMatrix = computeVirtualMatrix(finalItems, finalAllocations, finalQtyPerPage);
      const resolvedSlot = freshMatrix.find(s => s.itemType === itemId && s.index === targetIndex);
        // 🔍 LIMIT INTEGRITY CHECK: Calculate current claims vs configuration maximums
      const gateDetails = getGateStatusDetails() || {};
      const activeEventObj = updatedConfigSnap.val().events?.[gateDetails.activeEventId];
      const maxAllowedLimit = activeEventObj?.loots && activeEventObj.loots[itemId] !== undefined ? activeEventObj.loots[itemId] : 0;
      const userClaimedCount = freshMatrix.filter(s => s.itemType === itemId && s.name === finalRosterName).length;

      if (userClaimedCount >= maxAllowedLimit) {
        // 🚪 LIMIT EXHAUSTED KICKBACK: Auto-transfer them back to categories menu with a comprehensive notice
        const limitReachedBanner = `✅ **SUCCESSFULLY SECURED!**\n• Item Locked: **${resolvedSlot?.itemName} (Page ${resolvedSlot?.page}, Slot ${resolvedSlot?.slot})**\n\n🎉 **LIMIT COMPLETED**: You have fully filled your allocation quota (**${userClaimedCount}/${maxAllowedLimit}**) for this item category!...`;
        await renderItemCategoryView(interaction, finalRosterName, limitReachedBanner);
      } else {
        // 🕹️ STAY-AND-TAP CONTINUATION: Keep them locked on this exact grid view to rapid-fire their remaining bids
        const continuousBanner = `✅ **SUCCESSFULLY SECURED!**\n• Item Locked: **${resolvedSlot?.itemName} (Page ${resolvedSlot?.page}, Slot ${resolvedSlot?.slot})**\n• Running Total: **${userClaimedCount}/${maxAllowedLimit} Secured**\n\n*The ledger has updated. Tap another open item below to claim slot:*`;
        await renderSpecificSlotView(interaction, itemId, finalRosterName, continuousBanner);
      }

    } catch (err) {
      // Re-read current database layout parameters to recover slot details safely for collision receipts
      const updatedConfigSnap = await db.ref('settings/configuration').once('value');
      const updatedSessionSnap = await db.ref('auction/active_session').once('value');
      const finalItems = updatedConfigSnap.val().items || [];
      const finalAllocations = updatedSessionSnap.val().categoryAllocations || {};
      const finalQtyPerPage = updatedSessionSnap.val().qtyPerPage || 4;
      const freshMatrix = computeVirtualMatrix(finalItems, finalAllocations, finalQtyPerPage);
      const resolvedSlot = freshMatrix.find(s => s.itemType === itemId && s.index === targetIndex);
      if (err.message === 'COLLISION_DETECTED') {
        // 🎯 Safely parse coordinates directly from the dynamically compiled memory matrix 
        const collisionBanner = `⚠️ **SLOT OCCUPIED!** Another member claimed **Page ${resolvedSlot?.page || '?'}, Slot ${resolvedSlot?.slot || '?'}** right before you tapped.\n\n*No layout cells were overwritten. Try claiming another item below:*`;

        // Loop back smoothly inside that SAME button view so they can try an adjacent button instantly
        await renderSpecificSlotView(interaction, itemId, finalRosterName, collisionBanner);
      } else {
        console.error("Button Matrix Open Loop Step 3 Exception Caught:", err.message);
        await interaction.editReply({ content: '❌ Critical error executing real-time database ledger updates.', components: [] });
      }
    }
  }
}